const fs = require('fs');
const path = require('path');

function normalizeStoresData(rawStores) {
  const countries = {};

  // Deduplicate set: `${brand}|${country}|${website}`
  const seen = new Set();

  rawStores.forEach(store => {
    const key = `${store.brand}|${store.country}|${store.website}`;
    if (seen.has(key)) return; // skip duplicates
    seen.add(key);

    const countryCode = store.country.toUpperCase();

    if (!countries[countryCode]) {
      countries[countryCode] = { stores: [] };
    }

    countries[countryCode].stores.push({
      name: store.brand,
      url: store.website,
      notes: store.notes || '',
      source: store.source || 'manual',
      lastVerified: store.lastVerified || null
    });
  });

  return countries;
}

function loadData() {
  const rawDataPath = path.join(__dirname, '../../data/rawData.json'); // flat list
  const storesFilePath = path.join(__dirname, '../../data/stores.json'); // output file

  console.log('Loading raw stores data from:', rawDataPath);

  let rawStores = [];
  try {
    const rawContent = fs.readFileSync(rawDataPath, 'utf-8');
    rawStores = JSON.parse(rawContent);
  } catch (err) {
    console.error('Error loading rawData.json:', err);
    return { countries: {} };
  }

  const normalizedCountries = normalizeStoresData(rawStores);

  const output = {
    _meta: {
      note: '⚠️ Auto-generated by loadData.js — do not edit manually'
    },
    countries: normalizedCountries
  };

  // Check if file exists and content is identical
  let writeFile = true;
  if (fs.existsSync(storesFilePath)) {
    try {
      const existingContent = fs.readFileSync(storesFilePath, 'utf-8');
      const existingJson = JSON.parse(existingContent);

      // Compare stringified JSON (cheap but effective)
      if (JSON.stringify(existingJson) === JSON.stringify(output)) {
        writeFile = false; // nothing changed, no need to overwrite
        console.log('No changes detected, stores.json not updated.');
      }
    } catch (err) {
      console.warn('Could not read existing stores.json, will overwrite.');
    }
  }

  if (writeFile) {
    try {
      fs.writeFileSync(storesFilePath, JSON.stringify(output, null, 2), 'utf-8');
      console.log('Stores Updated written to stores.json');
    } catch (err) {
      console.error('Error writing stores.json:', err);
    }
  }

  return output;
}

module.exports = loadData;
